### ISSUE TITLE
http://antcat.org/database_scripts/orphaned_protonyms

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#430] opened 2018-07-29 14:44 UTC
@jonkerz I am looking through the scripts (it is not easy to find which scripts still have erros to correct) and found this one: http://antcat.org/database_scripts/orphaned_protonyms
it appears these name IDs are no longer in the database but the script is still showing the results.  Is there something I need to do or should you delete these?

**Comment by jonkerz** [comment] 2018-08-01 20:25
@bpescador 

> Is there something I need to do or should you delete these?

You don't have to do anything, actually it's not even possible to delete these in the GUI.

They are pretty harmless, but I'll delete them by script.

> it is not easy to find which scripts still have erros to correct

Yupp, the plan is to a) make sure most of the "regression-test" scripts never have to be checked because it should be fixed in the code before the issues even happen, and b) have a single list for the ones that cannot be automatically fixed and let editors fix them.

**Comment by jonkerz** [comment] 2018-08-01 20:26
Deletion script:

```ruby
jonkerz = User.find 60
Activity.execute_script_activity jonkerz, 'Delete orphaned protonyms, see %github430'

Protonym.where("id NOT IN (SELECT protonym_id FROM taxa)").find_each do |protonym|
  protonym.destroy
end
```

**Comment by bpescador** [comment] 2018-08-01 21:02
@jonkerz Sounds like a good plan and yes, please run your deletion script on those orphaned_protonyms

**Closed** 2019-04-03 02:24 UTC
Labels: script
