### ISSUE TITLE
obsolete combination

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#236] opened 2017-09-06 13:54 UTC
For a taxon, when the status is changed to "obsolete combination",  the current combination needs to be indicated and this is not the same as "current valid name";  The current combination could be a junior synonym, etc.  

Thus when the status is "obsolete combination"  the field that is labeled Current Valid Name should be changed to "Current Combination"  We may not need to indicate the current valid name of the obsolete combination since the current combination record should already indicate the current valid name.

**Comment by jonkerz** [comment] 2018-07-10 17:59
Closing as duplicate of #375.

**Closed by jonkerz** 2018-07-10 17:59 UTC
