### ISSUE TITLE
References: restore old search by author feature

### ISSUE THREAD

**Issue by flaviaesteves** [calacademy-research/antcat#136] opened 2016-04-10 04:38 UTC
Searching by an author on http://www.antcat.org/references
1. Typed author name (ex. Janet, C.)
2. Waited until the drop-down list of authors pops up.
3. No name in the drop-down list resembles typed name (the list shows: Andre, Ern.; Billen, J.P.J.; and so on)

Tried with Fisher, B. L., Ward, P., and also unrelated names on the drop-down list.

Search for article's title is working though.

**Comment by jonkerz** [comment] 2016-04-10 04:43
@flaviaesteves This is a known issue (it was changed back in December 2015). You currently have to query for author like this: `author:Janet` ([link](http://www.antcat.org/references/search?utf8=%E2%9C%93&q=author%3AJanet)). It's it supposed to be converted into a search form in the future.

**Comment by flaviaesteves** [comment] 2016-04-10 04:49
Thanks Fredrik. Is it possible to get rid of the "author:" requirement in a search for authors? Before open the issue I look at the search help, but that requirement was not intuitive for me.

**Comment by jonkerz** [comment] 2016-04-11 06:08
Note that this has not been pushed to the live site yet, which means that the links below will not work until it has, but it's scheduled for v2.0.1. Please close this issue after you have confirmed that it works as intended on the live site.

@flaviaesteves I've restored the old "Search by author(s)" functionality ([example](http://antcat.org/references/search?utf8=%E2%9C%93&search_type=author&q=&author_q=Janet%2C+C.%3B+)). The keywords feature is still in the code (including `author:janet`), but you do not have to use it. The reference search help page has also been updated with a "Simple reference search" section ([link](http://antcat.org/references/search_help)).

Commits: 68c7787df26defb5adaf67c466ab91af7879be9f, 047695037f9fae48dbc69558b2051758b7e143b1

**Comment by jonkerz** [comment] 2016-04-14 09:06
@flaviaesteves It's live.

**Closed** 2016-05-04 07:40 UTC
Labels: feature
